version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@3.1.1
  eb: circleci/aws-elastic-beanstalk@2.0.1

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install
      - aws-cli/setup
      - eb/setup
      - run:
          name: frontend install
          command: |
            npm run frontend:install
      - run:
          name: frontend build
          command: |
            npm run frontend:build
      - run:
          name: frontend deploy
          command: |
            npm run frontend:deploy
      - run:
          name: api install
          command: |
            npm run api:install
      - run:
          name: api build
          command: |
            npm run api:build
      - run:
          name: api deploy
          command: |
            npm run api:deploy
workflows:
  main:
    jobs:
      - build:
          filters:
            branches:
              only: master 